### ISSUE TITLE
Unnecessary to enabled check

### ISSUE THREAD

**Issue by sfnelson** [katalyst/katalyst-basic-auth#1]
https://github.com/katalyst/katalyst-basic-auth/blob/6aade627154f2d4fdcaaaa30c6b9e02e42da90e9/lib/katalyst/basic/auth/middleware.rb#L20

**Comment by sfnelson** [comment]
Middleware is only installed when enabled (rails.rb)

**Comment by sobakasu** [comment]
fixed by #4
